language: php

php:
  - 7.0
  - hhvm

sudo: required
dist: xenial
group: edge

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer install ${COMPOSER_FLAGS} --ignore-platform-reqs --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
