language: php

php:
  - 7.0
  - hhvm

dist: xenial

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer install ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
